In [1]:
import numpy as np
import pandas as pd
from sklearn import neighbors,metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv("car.data")

In [3]:
df

buying  maint  doors persons lug_boot saftey  class
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

In [4]:
df.head()

buying  maint doors persons lug_boot saftey  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [5]:
X=df[['buying','maint','saftey']].values

In [6]:
y=df['class']

In [7]:
lb=LabelEncoder()

In [8]:
for i in range(len(X[0])):
    X[:,i]=lb.fit_transform(X[:,i])

In [9]:
print(X)

[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


In [10]:
#converting y

label_maping={"unacc":0,
             "acc":1,
             "good":2,
             "vgood":3}
y=y.map(label_maping)

In [11]:
y

0       0
1       0
2       0
3       0
4       0
       ..
1723    2
1724    3
1725    0
1726    2
1727    3
Name: class, Length: 1728, dtype: int64

In [17]:
my_model=neighbors.KNeighborsClassifier(n_neighbors=25,weights='uniform')

In [18]:
X_tran,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [19]:
my_model.fit(X_tran,y_train)

KNeighborsClassifier(n_neighbors=25)

In [22]:
prediction=my_model.predict(X_test)

In [23]:
prediction

array([0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 2, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 2, 1, 3, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 3, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 2, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 2, 1, 0, 1, 0, 3, 0, 0,
       0, 0, 0, 0, 0, 3, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 2, 0,
       0, 3, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 1, 0,

In [24]:
acc=metrics.accuracy_score(y_test,prediction)

In [25]:
acc

0.7398843930635838

In [27]:
Result = pd.DataFrame({'Actual':y_test,'Predictions':prediction})

In [28]:
Result

Actual  Predictions
1215       0            0
783        0            0
1638       0            0
1271       0            2
52         0            0
...      ...          ...
166        0            0
981        0            0
944        1            1
692        1            1
1273       0            0

[346 rows x 2 columns]

In [38]:
print("Actual value :",y[693])

Actual value : 0


In [39]:
print("Predcited value :",my_model.predict(X)[693])

Predcited value : 0
